 #===========================================================================
# allowed DPIs
#===========================================================================
dpis:
  - 600
  - 254
  - 190
  - 127

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 5000
  - 10000
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 40000000
  - 100000000
  - 140000000

formats:
  - pdf
  - png
  - jpeg

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true

  - !ipMatch
    host: 127.0.0.1
    # Allow to all hosts
    mask: 0.0.0.0

layouts:
  #===========================================================================
  A4 portrait:
    mainPage:
      rotation: true
      pageSize: A4
      # backgroundPdf: '${configDir}/template.pdf'
      header:
        height: 1
      items:
        - !columns
          absoluteX: 10
          absoluteY: 828
          width: 575
          items:
            - !text
              align: center
              font: Helvetica
              fontSize: 24
              text: '${title}'
        - !map
          condition: hasTitle
          spacingAfter: 10
          width: 545
          height: 700
          absoluteX:25
          absoluteY:780
        - !map
          condition: hasNoTitle
          spacingAfter: 10
          width: 545
          height: 746
          absoluteX:25
          absoluteY:816
        - !columns
          condition: hasAttribution
          absoluteX: 150
          absoluteY: 55
          width: 100
          items:
            - !text
                font: Helvetica
                fontSize: 16
                text: 'Source(s): '
        - !columns
          condition: hasAttribution
          absoluteX: 250
          absoluteY: 51
          width: 250
          items:
            - !text
                font: Helvetica
                fontSize: 11
                text: '${dataOwner}'
        - !columns
          absoluteX: 25
          absoluteY: 45
          width: 180
          items:
            - !scalebar
              align: left
              maxSize: 180
              type: 'bar sub'
              intervals: 5
        - !columns
          absoluteX: 540
          absoluteY: 55
          width: 35
          items:
            - !image
              maxWidth: 35
              maxHeight: 35
              url: 'file://${configDir}/Arrow_North_CFCF.svg'
              rotation: '${rotation}'
    lastPage:
      items:
         - !columns
          condition: enableLegends
          absoluteX: 51
          absoluteY: 808
          width: 511
          items:
            - !legends
              inline: false
              defaultScale: 0.5
              maxHeight: 400
              maxWidth: 500
              iconMaxHeight: 0
              iconMaxWidth: 0
              horizontalAlignment: left
              columnMargin: 10
              classIndentation: 3
              classSpace: 5
              backgroundColor: white
              layerFontSize: 9
  #===========================================================================
  A4 landscape:
    mainPage:
      rotation: false
      pageSize: LEGAL
      landscape: true
      backgroundPdf: '${configDir}/template-landscape.pdf'
      items:
        - !map
          condition: hasTitle
          spacingAfter: 10
          width: 958
          height: 480
          absoluteX: 25
          absoluteY: 552
        - !map
          condition: hasNoTitle
          spacingAfter: 10
          width: 958
          height: 516
          absoluteX: 25
          absoluteY: 588
        - !columns
          absoluteX: 25
          absoluteY: 593
          width: 958
          items:
            - !text
              font: Helvetica
              align: center
              fontSize: 24
              text: '${title}'
        - !columns
          condition: hasAttribution
          absoluteX: 200
          absoluteY: 55
          width: 100
          items:
            - !text
                font: Helvetica
                fontSize: 16
                text: 'Source(s): '
        - !columns
          condition: hasAttribution
          absoluteX: 300
          absoluteY: 51
          width: 600
          items:
            - !text
                font: Helvetica
                fontSize: 11
                text: '${dataOwner}'
        - !columns
          absoluteX: 25
          absoluteY: 45
          width: 180
          items:
            - !scalebar
              align: left
              maxSize: 180
              type: 'bar sub'
              intervals: 5
        - !columns
          absoluteX: 960
          absoluteY: 48
          width: 35
          items:
            - !image
              maxWidth: 35
              maxHeight: 35
              url: 'file://${configDir}/Arrow_North_CFCF.svg'
              rotation: '${rotation}'
    lastPage:
      landscape: true
      items:
         - !columns
          condition: enableLegends
          absoluteX: 21
          absoluteY: 588
          width: 801
          items:
            - !legends
              inline: false
              defaultScale: 0.5
              maxHeight: 400
              maxWidth: 800
              iconMaxHeight: 0
              iconMaxWidth: 0
              horizontalAlignment: left
              columnMargin: 10
              classIndentation: 3
              classSpace: 5
              backgroundColor: white
              layerFontSize: 9
